---
- name: My playbook
  hosts: webservers
  become: true
  tasks:

  - name: Install docker.io  (state=present is optional)
    apt:
      name: docker.io
      state: present
      update_cache: yes
  - name: Install python3-pip
    apt:
      name: python3-pip
      state: present
  - name: Install docker
    pip: 
      name: docker
      state: present 
  - name: Install cyberxsecurity/dvwa
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      published_ports: "80:80"
      restart_policy: always
  - name: Start docker on VM restart 
    ansible.builtin.systemd:
      name: docker
      enabled: yes
